export type Problem = { name: string; difficulty: 'Easy' | 'Medium' | 'Hard' };

export const DIFF_COLOR: Record<string, string> = {
  Easy:   '#10B981',
  Medium: '#F59E0B',
  Hard:   '#EF4444',
};

export const CAT_COLOR: Record<string, string> = {
  'Arrays & Hashing':      '#6366F1',
  'Two Pointers':          '#10B981',
  'Sliding Window':        '#F59E0B',
  'Stack':                 '#EF4444',
  'Binary Search':         '#8B5CF6',
  'Linked List':           '#EC4899',
  'Trees':                 '#14B8A6',
  'Heap / Priority Queue': '#F97316',
  'Backtracking':          '#6366F1',
  'Graphs':                '#06B6D4',
  'Dynamic Programming':   '#8B5CF6',
  'Tries':                 '#EC4899',
};

export const PROBLEMS: Record<string, Problem[]> = {
  'Arrays & Hashing': [
    { name: 'Contains Duplicate',             difficulty: 'Easy'   },
    { name: 'Valid Anagram',                  difficulty: 'Easy'   },
    { name: 'Two Sum',                        difficulty: 'Easy'   },
    { name: 'Group Anagrams',                 difficulty: 'Medium' },
    { name: 'Top K Frequent Elements',        difficulty: 'Medium' },
    { name: 'Encode and Decode Strings',      difficulty: 'Medium' },
    { name: 'Product of Array Except Self',   difficulty: 'Medium' },
    { name: 'Valid Sudoku',                   difficulty: 'Medium' },
    { name: 'Longest Consecutive Sequence',   difficulty: 'Medium' },
  ],
  'Two Pointers': [
    { name: 'Valid Palindrome',               difficulty: 'Easy'   },
    { name: 'Two Sum II',                     difficulty: 'Medium' },
    { name: '3Sum',                           difficulty: 'Medium' },
    { name: 'Container With Most Water',      difficulty: 'Medium' },
    { name: 'Trapping Rain Water',            difficulty: 'Hard'   },
  ],
  'Sliding Window': [
    { name: 'Best Time to Buy and Sell Stock',                       difficulty: 'Easy'   },
    { name: 'Longest Substring Without Repeating Characters',        difficulty: 'Medium' },
    { name: 'Longest Repeating Character Replacement',               difficulty: 'Medium' },
    { name: 'Permutation in String',                                 difficulty: 'Medium' },
    { name: 'Minimum Window Substring',                              difficulty: 'Hard'   },
    { name: 'Sliding Window Maximum',                                difficulty: 'Hard'   },
  ],
  'Stack': [
    { name: 'Valid Parentheses',               difficulty: 'Easy'   },
    { name: 'Min Stack',                       difficulty: 'Medium' },
    { name: 'Evaluate Reverse Polish Notation',difficulty: 'Medium' },
    { name: 'Generate Parentheses',            difficulty: 'Medium' },
    { name: 'Daily Temperatures',             difficulty: 'Medium' },
    { name: 'Car Fleet',                      difficulty: 'Medium' },
    { name: 'Largest Rectangle in Histogram', difficulty: 'Hard'   },
  ],
  'Binary Search': [
    { name: 'Binary Search',                        difficulty: 'Easy'   },
    { name: 'Search a 2D Matrix',                   difficulty: 'Medium' },
    { name: 'Koko Eating Bananas',                  difficulty: 'Medium' },
    { name: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium' },
    { name: 'Search in Rotated Sorted Array',       difficulty: 'Medium' },
    { name: 'Time Based Key-Value Store',           difficulty: 'Medium' },
    { name: 'Median of Two Sorted Arrays',          difficulty: 'Hard'   },
  ],
  'Linked List': [
    { name: 'Reverse Linked List',              difficulty: 'Easy'   },
    { name: 'Merge Two Sorted Lists',           difficulty: 'Easy'   },
    { name: 'Reorder List',                     difficulty: 'Medium' },
    { name: 'Remove Nth Node From End of List', difficulty: 'Medium' },
    { name: 'Copy List with Random Pointer',    difficulty: 'Medium' },
    { name: 'Add Two Numbers',                  difficulty: 'Medium' },
    { name: 'Linked List Cycle',                difficulty: 'Easy'   },
    { name: 'Find the Duplicate Number',        difficulty: 'Medium' },
    { name: 'LRU Cache',                        difficulty: 'Medium' },
    { name: 'Merge K Sorted Lists',             difficulty: 'Hard'   },
    { name: 'Reverse Nodes in K-Group',         difficulty: 'Hard'   },
  ],
  'Trees': [
    { name: 'Invert Binary Tree',                                        difficulty: 'Easy'   },
    { name: 'Maximum Depth of Binary Tree',                              difficulty: 'Easy'   },
    { name: 'Diameter of Binary Tree',                                   difficulty: 'Easy'   },
    { name: 'Balanced Binary Tree',                                      difficulty: 'Easy'   },
    { name: 'Same Tree',                                                 difficulty: 'Easy'   },
    { name: 'Subtree of Another Tree',                                   difficulty: 'Easy'   },
    { name: 'Lowest Common Ancestor of a BST',                           difficulty: 'Medium' },
    { name: 'Binary Tree Level Order Traversal',                         difficulty: 'Medium' },
    { name: 'Binary Tree Right Side View',                               difficulty: 'Medium' },
    { name: 'Count Good Nodes in Binary Tree',                           difficulty: 'Medium' },
    { name: 'Validate Binary Search Tree',                               difficulty: 'Medium' },
    { name: 'Kth Smallest Element in a BST',                             difficulty: 'Medium' },
    { name: 'Construct Binary Tree from Preorder and Inorder Traversal', difficulty: 'Medium' },
    { name: 'Binary Tree Maximum Path Sum',                              difficulty: 'Hard'   },
    { name: 'Serialize and Deserialize Binary Tree',                     difficulty: 'Hard'   },
  ],
  'Heap / Priority Queue': [
    { name: 'Kth Largest Element in a Stream', difficulty: 'Easy'   },
    { name: 'Last Stone Weight',               difficulty: 'Easy'   },
    { name: 'K Closest Points to Origin',      difficulty: 'Medium' },
    { name: 'Kth Largest Element in an Array', difficulty: 'Medium' },
    { name: 'Task Scheduler',                  difficulty: 'Medium' },
    { name: 'Design Twitter',                  difficulty: 'Medium' },
    { name: 'Find Median from Data Stream',    difficulty: 'Hard'   },
  ],
  'Backtracking': [
    { name: 'Subsets',                               difficulty: 'Medium' },
    { name: 'Combination Sum',                       difficulty: 'Medium' },
    { name: 'Permutations',                          difficulty: 'Medium' },
    { name: 'Subsets II',                            difficulty: 'Medium' },
    { name: 'Combination Sum II',                    difficulty: 'Medium' },
    { name: 'Word Search',                           difficulty: 'Medium' },
    { name: 'Palindrome Partitioning',               difficulty: 'Medium' },
    { name: 'Letter Combinations of a Phone Number', difficulty: 'Medium' },
    { name: 'N-Queens',                              difficulty: 'Hard'   },
  ],
  'Graphs': [
    { name: 'Number of Islands',                                  difficulty: 'Medium' },
    { name: 'Clone Graph',                                        difficulty: 'Medium' },
    { name: 'Max Area of Island',                                 difficulty: 'Medium' },
    { name: 'Pacific Atlantic Water Flow',                        difficulty: 'Medium' },
    { name: 'Surrounded Regions',                                 difficulty: 'Medium' },
    { name: 'Rotting Oranges',                                    difficulty: 'Medium' },
    { name: 'Walls and Gates',                                    difficulty: 'Medium' },
    { name: 'Course Schedule',                                    difficulty: 'Medium' },
    { name: 'Course Schedule II',                                 difficulty: 'Medium' },
    { name: 'Redundant Connection',                               difficulty: 'Medium' },
    { name: 'Number of Connected Components in Undirected Graph', difficulty: 'Medium' },
    { name: 'Graph Valid Tree',                                   difficulty: 'Medium' },
    { name: 'Word Ladder',                                        difficulty: 'Hard'   },
  ],
  'Dynamic Programming': [
    { name: 'Climbing Stairs',                                    difficulty: 'Easy'   },
    { name: 'Min Cost Climbing Stairs',                           difficulty: 'Easy'   },
    { name: 'House Robber',                                       difficulty: 'Medium' },
    { name: 'House Robber II',                                    difficulty: 'Medium' },
    { name: 'Longest Palindromic Substring',                      difficulty: 'Medium' },
    { name: 'Palindromic Substrings',                             difficulty: 'Medium' },
    { name: 'Decode Ways',                                        difficulty: 'Medium' },
    { name: 'Coin Change',                                        difficulty: 'Medium' },
    { name: 'Maximum Product Subarray',                           difficulty: 'Medium' },
    { name: 'Word Break',                                         difficulty: 'Medium' },
    { name: 'Longest Increasing Subsequence',                     difficulty: 'Medium' },
    { name: 'Partition Equal Subset Sum',                         difficulty: 'Medium' },
    { name: 'Unique Paths',                                       difficulty: 'Medium' },
    { name: 'Longest Common Subsequence',                         difficulty: 'Medium' },
    { name: 'Best Time to Buy and Sell Stock with Cooldown',      difficulty: 'Medium' },
    { name: 'Coin Change II',                                     difficulty: 'Medium' },
    { name: 'Target Sum',                                         difficulty: 'Medium' },
    { name: 'Interleaving String',                                difficulty: 'Medium' },
    { name: 'Longest Increasing Path in a Matrix',                difficulty: 'Hard'   },
    { name: 'Distinct Subsequences',                              difficulty: 'Hard'   },
    { name: 'Edit Distance',                                      difficulty: 'Medium' },
    { name: 'Burst Balloons',                                     difficulty: 'Hard'   },
    { name: 'Regular Expression Matching',                        difficulty: 'Hard'   },
    { name: 'Jump Game',                                          difficulty: 'Medium' },
  ],
  'Tries': [
    { name: 'Implement Trie (Prefix Tree)',               difficulty: 'Medium' },
    { name: 'Design Add and Search Words Data Structure', difficulty: 'Medium' },
    { name: 'Word Search II',                            difficulty: 'Hard'   },
  ],
};

export const DAILY_FACTS = [
  "The first computer bug was a real moth — found trapped in a Harvard Mark II relay in 1947 by Grace Hopper's team.",
  "Git was built by Linus Torvalds in just 10 days in 2005 to manage the Linux kernel after a licensing dispute.",
  "Python was named after Monty Python's Flying Circus, not the snake. Guido van Rossum wanted something short and fun.",
  "The first website ever created is still live: info.cern.ch — launched by Tim Berners-Lee in 1991.",
  "Transformers — the architecture behind GPT/Gemini — came from the 2017 paper 'Attention Is All You Need' by 8 Google Brain researchers.",
  "Binary search was described in 1946, but the first bug-free published implementation didn't appear until 1962.",
  "O(n log n) is the theoretical lower bound for comparison-based sorting. You literally cannot go faster.",
  "The LeetCode Two Sum problem has been solved over 15 million times — it's the most attempted problem in history.",
  "Dijkstra wrote his shortest path algorithm in 20 minutes with pen and paper in a café — no computer needed.",
  "Hash tables have O(1) average time but O(n) worst case. That worst case is triggered by hash collisions.",
  "Backpropagation was invented in 1986, but neural nets only became practical in 2012 when AlexNet used GPUs.",
  "GPT-4 has an estimated 1.8 trillion parameters — 10x more than GPT-3.",
  "The RAG technique (Retrieval-Augmented Generation) lets LLMs access fresh knowledge without retraining.",
  "Redis achieves 1M+ operations per second by keeping everything in RAM — trading durability for pure speed.",
  "The CAP theorem: distributed systems can guarantee at most 2 of Consistency, Availability, Partition tolerance.",
  "Consistent hashing reduces remapped keys from O(n) to O(k/n) when a new node is added — used by DynamoDB.",
  "Docker containers share the host kernel, which is why they start in milliseconds vs minutes for VMs.",
  "'Dynamic programming' was deliberately named by Bellman to sound impressive and hide that he was doing math research.",
  "Quicksort is O(n log n) average but O(n²) worst case — and already-sorted data triggers the worst case with naive pivot.",
  "LRU Cache solution = HashMap + Doubly Linked List, giving O(1) for both get and put operations.",
  "BFS uses a queue (FIFO), DFS uses a stack (LIFO). That one data structure difference defines their entire behavior.",
  "The sliding window pattern converts O(n²) nested loop problems into O(n) with a running state window.",
  "Embeddings turn text into high-dimensional vectors — similar meaning = geometrically close points.",
  "LangChain's core idea: chain = prompt | LLM | output_parser — pipe syntax borrowed from Unix.",
  "WebRTC uses STUN/TURN servers to punch through NAT — that's the magic behind peer-to-peer video calls.",
  "The Fibonacci sequence naive recursion is O(2^n). One dict of memo makes it O(n). The classic DP improvement.",
  "Two Generals Problem (1975) proves some distributed consensus problems are mathematically impossible to solve perfectly.",
  "Facebook processes 100 billion+ messages per day on WhatsApp — all through distributed systems.",
  "Layer Normalization in transformers prevents vanishing gradients — the main reason deep networks failed before 2015.",
  "The average developer reads 10x more code than they write — naming things well IS performance optimization.",
  "LoRA (Low-Rank Adaptation) fine-tunes just 0.1% of model parameters but achieves ~95% of full fine-tuning quality.",
  "Vector databases like pgvector use HNSW (Hierarchical Navigable Small World) graphs for approximate nearest-neighbor search.",
  "Microservices each have their own DB by convention — this is called 'database per service' and prevents coupling.",
];
